name: docker-s3-volume CI

on:
  workflow_dispatch:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.OPS_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.OPS_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.OPS_AWS_DEFAULT_REGION }}
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: docker-s3-volume
          IMAGE_TAG: latest
        run: |
          docker build . -f Dockerfile -t $ECR_REGISTRY/$ECR_REPOSITORY:staging
            docker image tag $ECR_REGISTRY/$ECR_REPOSITORY:staging $ECR_REGISTRY/$ECR_REPOSITORY:${{ github.sha }}
            [ ${{ github.ref_name }} == "master" ] && docker image tag $ECR_REGISTRY/$ECR_REPOSITORY:staging $ECR_REGISTRY/$ECR_REPOSITORY:latest
            docker push -a $ECR_REGISTRY/$ECR_REPOSITORY
